"""empty message

Revision ID: 6c035404d45c
Revises: 
Create Date: 2025-11-06 15:28:09.274718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c035404d45c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabs_id'), 'tabs', ['id'], unique=False)
    op.create_index(op.f('ix_tabs_song_name'), 'tabs', ['song_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tabs_song_name'), table_name='tabs')
    op.drop_index(op.f('ix_tabs_id'), table_name='tabs')
    op.drop_table('tabs')
    # ### end Alembic commands ###
