"""empty message

Revision ID: a448cef36374
Revises: b419b3a0d5a4
Create Date: 2025-11-12 15:49:25.591938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a448cef36374'
down_revision: Union[str, None] = 'b419b3a0d5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('album', sa.String(length=100), nullable=False))
    op.add_column('tabs', sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty_type', native_enum=False), nullable=True))
    op.add_column('tabs', sa.Column('description', sa.String(length=500), nullable=False))
    op.add_column('tabs', sa.Column('lyrics_included', sa.Boolean(), nullable=False))
    op.add_column('tabs', sa.Column('downloads', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'downloads')
    op.drop_column('tabs', 'lyrics_included')
    op.drop_column('tabs', 'description')
    op.drop_column('tabs', 'difficulty')
    op.drop_column('tabs', 'style')
    op.drop_column('tabs', 'album')
    # ### end Alembic commands ###
