"""empty message

Revision ID: b419b3a0d5a4
Revises: 6c035404d45c
Create Date: 2025-11-07 12:00:09.906379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b419b3a0d5a4'
down_revision: Union[str, None] = '6c035404d45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('genre', sa.Enum('ROCK', 'JAZZ', 'INDIE', 'POP', 'METAL', name='genre_type', native_enum=False), nullable=True))
    op.add_column('tabs', sa.Column('style', sa.Enum('FINGER_PICKING', 'STRUMMING', name='style_type', native_enum=False), nullable=True))
    op.add_column('tabs', sa.Column('file_key', sa.String(length=255), nullable=False))
    op.add_column('tabs', sa.Column('file_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'file_name')
    op.drop_column('tabs', 'file_key')
    op.drop_column('tabs', 'style')
    op.drop_column('tabs', 'genre')
    # ### end Alembic commands ###
