"""empty message

Revision ID: d1ddbb232c0c
Revises: dbf9d56926cb
Create Date: 2025-11-16 14:42:13.120728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ddbb232c0c'
down_revision: Union[str, None] = 'dbf9d56926cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabs', 'artist',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tabs', 'album',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tabs', 'genre',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CLASSICAL', 'COUNTRY', 'FOLK', 'INDIE', 'METAL', 'POP', 'ROCK', name='genre_type', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabs', 'genre',
               existing_type=sa.Enum('CLASSICAL', 'COUNTRY', 'FOLK', 'INDIE', 'METAL', 'POP', 'ROCK', name='genre_type', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('tabs', 'album',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tabs', 'artist',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
