"""empty message

Revision ID: dbf9d56926cb
Revises: a448cef36374
Create Date: 2025-11-16 14:40:23.674265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf9d56926cb'
down_revision: Union[str, None] = 'a448cef36374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabs', 'genre',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('CLASSICAL', 'COUNTRY', 'FOLK', 'INDIE', 'METAL', 'POP', 'ROCK', name='genre_type', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabs', 'genre',
               existing_type=sa.Enum('CLASSICAL', 'COUNTRY', 'FOLK', 'INDIE', 'METAL', 'POP', 'ROCK', name='genre_type', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###
